"""
NNUE Weight Training Pipeline for Cave Chess Engine

This script trains NNUE (Efficiently Updatable Neural Network) weights
from self-play training data generated by the Rust engine.

Architecture:
  Input: HalfKP features (king position x piece position pairs)
         ~40,960 sparse input features
  Hidden 1: 256 neurons (ClippedReLU)
  Hidden 2: 32 neurons (ClippedReLU)
  Output: 1 scalar (centipawn evaluation)

Usage:
  python train.py --data training_data.bin --output weights.nnue
  python train.py --data training_data.bin --output weights.nnue --epochs 100 --lr 0.001

Requirements:
  pip install torch numpy
"""

import argparse
import struct
import sys
from pathlib import Path

try:
    import torch
    import torch.nn as nn
    import torch.optim as optim
    from torch.utils.data import Dataset, DataLoader
    import numpy as np
except ImportError:
    print("Error: PyTorch and NumPy are required.")
    print("Install with: pip install torch numpy")
    sys.exit(1)


# --- NNUE Architecture ---

# HalfKP feature size: 64 king squares * 64 squares * 10 piece types = 40960
# (5 piece types x 2 colors, excluding kings)
NUM_FEATURES = 64 * 64 * 10
HIDDEN_1 = 256
HIDDEN_2 = 32


class ClippedReLU(nn.Module):
    """ReLU clamped to [0, 1] — standard in NNUE architectures"""
    def forward(self, x):
        return torch.clamp(x, 0.0, 1.0)


class NNUE(nn.Module):
    def __init__(self):
        super().__init__()
        self.input_layer = nn.Linear(NUM_FEATURES, HIDDEN_1)
        self.hidden1 = nn.Linear(HIDDEN_1 * 2, HIDDEN_2)  # *2 for both perspectives
        self.output = nn.Linear(HIDDEN_2, 1)
        self.clipped_relu = ClippedReLU()

    def forward(self, white_features, black_features):
        # Process each perspective through the shared input layer
        w = self.clipped_relu(self.input_layer(white_features))
        b = self.clipped_relu(self.input_layer(black_features))

        # Concatenate both perspectives
        combined = torch.cat([w, b], dim=1)

        # Hidden layers
        x = self.clipped_relu(self.hidden1(combined))
        x = self.output(x)
        return x


# --- Training Data ---

class ChessDataset(Dataset):
    """
    Reads training data generated by the engine's selfplay command.

    Binary format (per entry):
      - 4 bytes: number of active white features (u32)
      - N * 2 bytes: white feature indices (u16 each)
      - 4 bytes: number of active black features (u32)
      - M * 2 bytes: black feature indices (u16 each)
      - 4 bytes: target evaluation (i32, centipawns)
      - 1 byte: game result (0=black win, 1=draw, 2=white win)
    """

    def __init__(self, filepath):
        self.entries = []
        self._load(filepath)

    def _load(self, filepath):
        path = Path(filepath)
        if not path.exists():
            print(f"Training data file not found: {filepath}")
            print("Generate training data with: ./cave-chess selfplay --games 50000 --depth 8 --output training_data.bin")
            sys.exit(1)

        data = path.read_bytes()
        offset = 0

        while offset < len(data):
            try:
                # White features
                num_w = struct.unpack_from('<I', data, offset)[0]
                offset += 4
                w_indices = []
                for _ in range(num_w):
                    idx = struct.unpack_from('<H', data, offset)[0]
                    w_indices.append(idx)
                    offset += 2

                # Black features
                num_b = struct.unpack_from('<I', data, offset)[0]
                offset += 4
                b_indices = []
                for _ in range(num_b):
                    idx = struct.unpack_from('<H', data, offset)[0]
                    b_indices.append(idx)
                    offset += 2

                # Target eval
                target = struct.unpack_from('<i', data, offset)[0]
                offset += 4

                # Game result
                result = struct.unpack_from('<B', data, offset)[0]
                offset += 1

                self.entries.append((w_indices, b_indices, target, result))
            except struct.error:
                break

        print(f"Loaded {len(self.entries)} training positions from {filepath}")

    def __len__(self):
        return len(self.entries)

    def __getitem__(self, idx):
        w_indices, b_indices, target, result = self.entries[idx]

        # Create sparse feature vectors
        w_features = torch.zeros(NUM_FEATURES)
        b_features = torch.zeros(NUM_FEATURES)

        for i in w_indices:
            if i < NUM_FEATURES:
                w_features[i] = 1.0
        for i in b_indices:
            if i < NUM_FEATURES:
                b_features[i] = 1.0

        # Blend search eval with game result for target
        # This is standard in NNUE training — result provides ground truth,
        # eval provides positional nuance
        eval_cp = target / 100.0  # Convert centipawns to pawns
        result_score = (result - 1.0)  # -1, 0, 1

        # Sigmoid blend
        target_val = 0.5 * eval_cp + 0.5 * result_score

        return w_features, b_features, torch.tensor([target_val], dtype=torch.float32)


# --- Training Loop ---

def train(args):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Training on: {device}")

    dataset = ChessDataset(args.data)
    if len(dataset) == 0:
        print("No training data. Exiting.")
        return

    dataloader = DataLoader(dataset, batch_size=args.batch_size, shuffle=True, num_workers=0)

    model = NNUE().to(device)
    optimizer = optim.Adam(model.parameters(), lr=args.lr)
    criterion = nn.MSELoss()

    print(f"Model parameters: {sum(p.numel() for p in model.parameters()):,}")
    print(f"Training for {args.epochs} epochs, batch size {args.batch_size}")

    for epoch in range(args.epochs):
        total_loss = 0.0
        batches = 0

        for w_feat, b_feat, target in dataloader:
            w_feat, b_feat, target = w_feat.to(device), b_feat.to(device), target.to(device)

            optimizer.zero_grad()
            output = model(w_feat, b_feat)
            loss = criterion(output, target)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()
            batches += 1

        avg_loss = total_loss / max(batches, 1)
        print(f"Epoch {epoch + 1}/{args.epochs} — Loss: {avg_loss:.6f}")

    # Export weights
    export_nnue(model, args.output)
    print(f"Weights saved to {args.output}")


def export_nnue(model, filepath):
    """Export model weights in a simple binary format readable by the Rust engine."""
    path = Path(filepath)

    with open(path, 'wb') as f:
        # Magic header
        f.write(b'CAVE')
        # Version
        f.write(struct.pack('<I', 1))
        # Architecture: input_size, hidden1, hidden2
        f.write(struct.pack('<III', NUM_FEATURES, HIDDEN_1, HIDDEN_2))

        # Write each layer's weights and biases
        for name, param in model.named_parameters():
            data = param.detach().cpu().numpy().astype(np.float32)
            f.write(struct.pack('<I', data.size))
            f.write(data.tobytes())

    print(f"Exported {path.stat().st_size:,} bytes")


# --- Entry Point ---

def main():
    parser = argparse.ArgumentParser(description='Train NNUE weights for Cave Chess Engine')
    parser.add_argument('--data', required=True, help='Path to training data (binary format)')
    parser.add_argument('--output', default='weights.nnue', help='Output weights file')
    parser.add_argument('--epochs', type=int, default=50, help='Training epochs')
    parser.add_argument('--batch-size', type=int, default=1024, help='Batch size')
    parser.add_argument('--lr', type=float, default=0.001, help='Learning rate')
    args = parser.parse_args()

    train(args)


if __name__ == '__main__':
    main()
